# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: this thing you're doing
email: c.carl.miller@gmail.com
# description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
#baseurl: "/cv" # the subpath of your site, e.g. /blog
url: "http://cv.milleria.org" # the base hostname & protocol for your site
twitter_username: null
github_username:  null
# markdown: kramdown
# =======
# Site settings
title: C.C. Miller - web app CV
# title: wacv
tag_text: C.C. Miller - web app CV
# tag_text: wacv
description: C.C. Miller - web app CV
# description: wacv
# url: "http://localhost/cv"

# Build settings
markdown: kramdown

exclude: ["README.md","src-css","src-scripts","src-img","node_modules","gulpfile.js","package.json"]